// <auto-generated />
namespace SertzHir.Services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PersonGender_Updated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PersonGender_Updated));
        
        string IMigrationMetadata.Id
        {
            get { return "201812240332244_Person-Gender_Updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
