// <auto-generated />
namespace SertzHir.Services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PersonGender_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PersonGender_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201812240324316_Person-Gender_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
